# Copyright (C) 2026 KJ7NYE
#
# Pre-build script: read data/tracker_conf.json and emit a generated header
# containing the JSON as a C raw-string literal so it can be written to
# LittleFS/SPIFFS on first boot. Used by nRF52 variants which have no
# PlatformIO `uploadfs` equivalent — the embedded JSON is the source of
# truth for first-boot defaults instead of a separately-flashed FS image.
#
# Output: include/generated/default_config_embed.h (gitignored).
# Input:  data/tracker_conf.json (the same file ESP32 builds upload via uploadfs).

import os

Import("env")

INPUT       = "data/tracker_conf.json"
OUTPUT_DIR  = "include/generated"
OUTPUT      = os.path.join(OUTPUT_DIR, "default_config_embed.h")
DELIM       = "CFGJSON"   # raw-string delimiter; vanishingly unlikely to collide

if not os.path.exists(INPUT):
    print(f"[embed_config] WARNING: {INPUT} not found — skipping; first-boot writer will fall back to setDefaultValues()")
else:
    with open(INPUT, "r", encoding="utf-8") as f:
        content = f.read()

    # Defensive collision check: a JSON string value could in principle contain
    # the closing delimiter. Bail loudly rather than emitting a malformed header.
    closing = f"){DELIM}\""
    if closing in content:
        raise SystemExit(f"[embed_config] ERROR: input contains raw-string delimiter '{closing}'; pick a different DELIM in tools/embed_config.py")

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    new_text = (
        f"// Auto-generated by tools/embed_config.py — DO NOT EDIT.\n"
        f"// Source: {INPUT}\n"
        f"#pragma once\n\n"
        f"static const char DEFAULT_CONFIG_JSON[] = R\"{DELIM}(\n"
        f"{content}\n"
        f"){DELIM}\";\n"
    )

    # Skip the write when contents are unchanged. Rewriting the header bumps
    # its mtime, which makes SCons recompile every TU that includes it
    # (configuration.cpp + transitive deps) on every build — slow and
    # unnecessary when data/tracker_conf.json hasn't changed.
    existing = None
    if os.path.exists(OUTPUT):
        with open(OUTPUT, "r", encoding="utf-8") as f:
            existing = f.read()
    if existing == new_text:
        print(f"[embed_config] {OUTPUT} unchanged ({len(content)} bytes), skipping rewrite")
    else:
        with open(OUTPUT, "w", encoding="utf-8", newline="\n") as f:
            f.write(new_text)
        print(f"[embed_config] wrote {OUTPUT} ({len(content)} bytes from {INPUT})")
